import json
from django.core.management.base import BaseCommand
from django.utils.text import slugify
from django.utils.dateparse import parse_date
from api.models import JobCategory, Job
from datetime import date, timedelta

class Command(BaseCommand):
    help = 'Import 38+ jobs from JSON file'

    def handle(self, *args, **options):
        # Create default categories first
        categories = {
            'web': {'name': 'Web Development', 'icon': 'Code2'},
            'backend': {'name': 'Backend Development', 'icon': 'Server'},
            'frontend': {'name': 'Frontend Development', 'icon': 'Layout'},
            'mobile': {'name': 'Mobile Development', 'icon': 'Smartphone'},
            'database': {'name': 'Database', 'icon': 'Database'},
            'data_science': {'name': 'Data Science', 'icon': 'BarChart3'},
            'ai_ml': {'name': 'AI/ML', 'icon': 'Brain'},
            'devops': {'name': 'DevOps', 'icon': 'Cloud'},
            'design': {'name': 'Design', 'icon': 'Palette'},
            'gaming': {'name': 'Gaming', 'icon': 'Gamepad2'},
            'iot': {'name': 'IoT', 'icon': 'Wifi'},
        }
        
        category_objs = {}
        for key, cat_data in categories.items():
            cat, created = JobCategory.objects.get_or_create(
                name=cat_data['name'],
                defaults={'slug': slugify(cat_data['name']), 'icon': cat_data['icon']}
            )
            category_objs[key] = cat
            self.stdout.write(self.style.SUCCESS(f'Category ready: {cat.name}'))
        
        # Jobs data
        jobs_data = [
            # Web Development
            {
                'title': 'Web Developer',
                'category': 'web',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 300000,
                'salary_max': 600000,
                'description': 'We are looking for a talented Web Developer to create amazing websites and web applications.',
                'requirements': 'Knowledge of HTML, CSS, JavaScript. Basic understanding of web development concepts.',
                'responsibilities': 'Build responsive websites, collaborate with designers, optimize applications for speed.',
                'required_skills': ['HTML', 'CSS', 'JavaScript', 'React', 'Git'],
                'positions_available': 5,
                'is_featured': True,
            },
            {
                'title': 'Frontend Developer',
                'category': 'frontend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 650000,
                'description': 'Create beautiful and responsive user interfaces using modern frontend technologies.',
                'requirements': 'Strong knowledge of HTML, CSS, JavaScript. Familiarity with React or Vue.',
                'responsibilities': 'Build reusable components, ensure UI/UX best practices, optimize performance.',
                'required_skills': ['HTML5', 'CSS3', 'JavaScript', 'React', 'Tailwind CSS'],
                'positions_available': 4,
                'is_featured': True,
            },
            {
                'title': 'React Developer',
                'category': 'frontend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Build modern web applications using React.js ecosystem.',
                'requirements': 'Knowledge of React.js, JavaScript ES6+, state management.',
                'responsibilities': 'Develop React components, integrate APIs, optimize performance.',
                'required_skills': ['React', 'JavaScript', 'Redux', 'HTML5', 'CSS3'],
                'positions_available': 3,
                'is_featured': True,
            },
            {
                'title': 'Next.js Developer',
                'category': 'frontend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 750000,
                'description': 'Build server-side rendered React applications using Next.js.',
                'requirements': 'Knowledge of React, Next.js, server-side rendering concepts.',
                'responsibilities': 'Develop Next.js applications, implement SSR/SSG, optimize SEO.',
                'required_skills': ['React', 'Next.js', 'TypeScript', 'Tailwind CSS'],
                'positions_available': 2,
            },
            {
                'title': 'Vue.js Developer',
                'category': 'frontend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 650000,
                'description': 'Build interactive web applications using Vue.js framework.',
                'requirements': 'Knowledge of Vue.js, Vuex, Vue Router.',
                'responsibilities': 'Develop Vue components, manage state with Vuex, integrate APIs.',
                'required_skills': ['Vue.js', 'Vuex', 'JavaScript', 'HTML5', 'CSS3'],
                'positions_available': 2,
            },
            {
                'title': 'JavaScript Developer',
                'category': 'frontend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 600000,
                'description': 'Write clean, efficient JavaScript code for web applications.',
                'requirements': 'Strong JavaScript fundamentals, understanding of ES6+ features.',
                'responsibilities': 'Write JavaScript code, debug issues, optimize performance.',
                'required_skills': ['JavaScript', 'ES6+', 'HTML5', 'CSS3', 'Git'],
                'positions_available': 3,
            },
            {
                'title': 'Tailwind/Bootstrap Developer',
                'category': 'frontend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 300000,
                'salary_max': 550000,
                'description': 'Create stunning responsive designs using Tailwind CSS and Bootstrap.',
                'requirements': 'Knowledge of CSS frameworks, responsive design principles.',
                'responsibilities': 'Build responsive layouts, implement designs, ensure cross-browser compatibility.',
                'required_skills': ['Tailwind CSS', 'Bootstrap', 'HTML5', 'CSS3', 'JavaScript'],
                'positions_available': 2,
            },
            
            # Backend Development
            {
                'title': 'Python Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Build robust backend systems using Python.',
                'requirements': 'Python programming knowledge, basic understanding of databases.',
                'responsibilities': 'Develop APIs, work with databases, write efficient Python code.',
                'required_skills': ['Python', 'Django', 'Flask', 'PostgreSQL', 'Git'],
                'positions_available': 5,
                'is_featured': True,
            },
            {
                'title': 'Backend Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Build scalable backend services and APIs.',
                'requirements': 'Knowledge of any backend language, basic API concepts.',
                'responsibilities': 'Develop REST APIs, integrate databases, ensure security.',
                'required_skills': ['Python/Java/Node.js', 'SQL', 'REST API', 'Git'],
                'positions_available': 4,
                'is_featured': True,
            },
            {
                'title': 'Backend Lead',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'lead',
                'salary_min': 1500000,
                'salary_max': 2500000,
                'description': 'Lead backend development team and architect scalable solutions.',
                'requirements': '5+ years experience, strong system design skills, team leadership.',
                'responsibilities': 'Lead backend team, design architecture, mentor junior developers.',
                'required_skills': ['Python/Java', 'System Design', 'AWS', 'Microservices', 'Leadership'],
                'positions_available': 1,
            },
            {
                'title': 'Java Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Build enterprise applications using Java.',
                'requirements': 'Java programming knowledge, OOP concepts.',
                'responsibilities': 'Develop Java applications, work with databases, write unit tests.',
                'required_skills': ['Java', 'Spring Boot', 'MySQL', 'Maven', 'Git'],
                'positions_available': 3,
            },
            {
                'title': 'Java Spring Boot Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 750000,
                'description': 'Build microservices using Spring Boot framework.',
                'requirements': 'Java and Spring Boot knowledge, REST API concepts.',
                'responsibilities': 'Develop Spring Boot microservices, integrate with databases.',
                'required_skills': ['Java', 'Spring Boot', 'Spring MVC', 'MySQL', 'Maven'],
                'positions_available': 2,
            },
            {
                'title': 'Java Swing Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 600000,
                'description': 'Build desktop applications using Java Swing.',
                'requirements': 'Java programming, Swing framework knowledge.',
                'responsibilities': 'Develop desktop applications, create user interfaces.',
                'required_skills': ['Java', 'Swing', 'MySQL', 'JDBC'],
                'positions_available': 2,
            },
            {
                'title': 'Python Django Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 420000,
                'salary_max': 720000,
                'description': 'Build web applications using Django framework.',
                'requirements': 'Python and Django knowledge, basic web concepts.',
                'responsibilities': 'Develop Django applications, work with ORM, build APIs.',
                'required_skills': ['Python', 'Django', 'Django REST', 'PostgreSQL', 'Git'],
                'positions_available': 3,
                'is_featured': True,
            },
            {
                'title': 'API Engineer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Design and build robust APIs.',
                'requirements': 'API design concepts, REST principles.',
                'responsibilities': 'Design RESTful APIs, document endpoints, ensure security.',
                'required_skills': ['REST API', 'Python/Node.js', 'PostgreSQL', 'Swagger'],
                'positions_available': 2,
            },
            {
                'title': 'Go Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 800000,
                'description': 'Build high-performance backend services using Go.',
                'requirements': 'Go programming knowledge, concurrent programming concepts.',
                'responsibilities': 'Develop Go microservices, optimize performance.',
                'required_skills': ['Go', 'Gin/Echo', 'PostgreSQL', 'REST API'],
                'positions_available': 2,
            },
            {
                'title': 'Senior Backend Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'senior',
                'salary_min': 1200000,
                'salary_max': 2000000,
                'description': 'Architect and build complex backend systems.',
                'requirements': '4+ years experience, strong system design, cloud knowledge.',
                'responsibilities': 'Architect backend systems, optimize performance, mentor team.',
                'required_skills': ['Python/Java/Go', 'System Design', 'AWS', 'Microservices'],
                'positions_available': 2,
            },
            {
                'title': 'PHP Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 600000,
                'description': 'Build web applications using PHP.',
                'requirements': 'PHP programming knowledge, basic web concepts.',
                'responsibilities': 'Develop PHP applications, work with databases.',
                'required_skills': ['PHP', 'MySQL', 'HTML5', 'CSS3', 'Git'],
                'positions_available': 3,
            },
            {
                'title': 'PHP Laravel Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 380000,
                'salary_max': 650000,
                'description': 'Build modern web applications using Laravel framework.',
                'requirements': 'PHP and Laravel knowledge, MVC concepts.',
                'responsibilities': 'Develop Laravel applications, build REST APIs.',
                'required_skills': ['PHP', 'Laravel', 'MySQL', 'REST API', 'Git'],
                'positions_available': 2,
            },
            {
                'title': 'MERN Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 750000,
                'description': 'Build full-stack applications using MERN stack.',
                'requirements': 'JavaScript, React, Node.js, MongoDB knowledge.',
                'responsibilities': 'Develop full-stack apps, build REST APIs.',
                'required_skills': ['MongoDB', 'Express.js', 'React', 'Node.js', 'JavaScript'],
                'positions_available': 3,
                'is_featured': True,
            },
            {
                'title': 'MEAN Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 750000,
                'description': 'Build full-stack applications using MEAN stack.',
                'requirements': 'JavaScript, Angular, Node.js, MongoDB knowledge.',
                'responsibilities': 'Develop full-stack apps, build REST APIs.',
                'required_skills': ['MongoDB', 'Express.js', 'Angular', 'Node.js', 'TypeScript'],
                'positions_available': 2,
            },
            {
                'title': 'PERN Developer',
                'category': 'backend',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 750000,
                'description': 'Build full-stack applications using PERN stack.',
                'requirements': 'JavaScript, React, Node.js, PostgreSQL knowledge.',
                'responsibilities': 'Develop full-stack apps, work with PostgreSQL.',
                'required_skills': ['PostgreSQL', 'Express.js', 'React', 'Node.js', 'JavaScript'],
                'positions_available': 2,
            },
            
            # Database
            {
                'title': 'Senior Database Engineer',
                'category': 'database',
                'employment_type': 'full_time',
                'experience_level': 'senior',
                'salary_min': 1200000,
                'salary_max': 2000000,
                'description': 'Manage and optimize database systems.',
                'requirements': '5+ years database experience, performance tuning skills.',
                'responsibilities': 'Design database schemas, optimize queries, ensure data integrity.',
                'required_skills': ['PostgreSQL', 'MySQL', 'Performance Tuning', 'Backup/Recovery'],
                'positions_available': 1,
            },
            {
                'title': 'PostgreSQL Developer',
                'category': 'database',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Work with PostgreSQL databases.',
                'requirements': 'SQL knowledge, basic database concepts.',
                'responsibilities': 'Write SQL queries, optimize database performance.',
                'required_skills': ['PostgreSQL', 'SQL', 'PL/pgSQL', 'Database Design'],
                'positions_available': 2,
            },
            
            # Data Science & AI
            {
                'title': 'Data Analyst',
                'category': 'data_science',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Analyze data and generate insights.',
                'requirements': 'Data analysis concepts, basic statistics.',
                'responsibilities': 'Analyze datasets, create visualizations, generate reports.',
                'required_skills': ['Python', 'Pandas', 'SQL', 'Data Visualization'],
                'positions_available': 2,
            },
            {
                'title': 'Data Scientist',
                'category': 'data_science',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 500000,
                'salary_max': 900000,
                'description': 'Apply machine learning to solve business problems.',
                'requirements': 'Statistics, Python, basic ML concepts.',
                'responsibilities': 'Build ML models, analyze data, create predictions.',
                'required_skills': ['Python', 'Pandas', 'Scikit-learn', 'Statistics', 'SQL'],
                'positions_available': 2,
                'is_featured': True,
            },
            {
                'title': 'Machine Learning Engineer',
                'category': 'ai_ml',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 500000,
                'salary_max': 900000,
                'description': 'Build and deploy machine learning models.',
                'requirements': 'Python, ML algorithms, basic deep learning.',
                'responsibilities': 'Develop ML models, preprocess data, evaluate models.',
                'required_skills': ['Python', 'TensorFlow/PyTorch', 'Scikit-learn', 'Pandas'],
                'positions_available': 2,
                'is_featured': True,
            },
            {
                'title': 'AI Engineer (NLP)',
                'category': 'ai_ml',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 550000,
                'salary_max': 950000,
                'description': 'Build Natural Language Processing solutions.',
                'requirements': 'Python, NLP concepts, basic ML.',
                'responsibilities': 'Develop NLP models, process text data.',
                'required_skills': ['Python', 'NLP', 'Transformers', 'TensorFlow/PyTorch'],
                'positions_available': 2,
            },
            
            # DevOps
            {
                'title': 'DevOps Architect',
                'category': 'devops',
                'employment_type': 'full_time',
                'experience_level': 'senior',
                'salary_min': 1500000,
                'salary_max': 2500000,
                'description': 'Design and implement DevOps infrastructure.',
                'requirements': '5+ years DevOps experience, cloud expertise.',
                'responsibilities': 'Design CI/CD pipelines, manage cloud infrastructure.',
                'required_skills': ['Docker', 'Kubernetes', 'AWS/GCP', 'Jenkins', 'Terraform'],
                'positions_available': 1,
            },
            {
                'title': 'AIOps Engineer',
                'category': 'devops',
                'employment_type': 'full_time',
                'experience_level': 'senior',
                'salary_min': 1200000,
                'salary_max': 2000000,
                'description': 'Implement AI-powered IT operations.',
                'requirements': 'DevOps experience, ML knowledge.',
                'responsibilities': 'Implement AIOps solutions, automate operations.',
                'required_skills': ['Python', 'ML', 'Prometheus', 'Grafana', 'Kubernetes'],
                'positions_available': 1,
            },
            
            # Gaming
            {
                'title': 'C/C++ Developer',
                'category': 'gaming',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 400000,
                'salary_max': 700000,
                'description': 'Build applications using C/C++.',
                'requirements': 'C/C++ programming knowledge.',
                'responsibilities': 'Write efficient C/C++ code, debug issues.',
                'required_skills': ['C', 'C++', 'Data Structures', 'Algorithms'],
                'positions_available': 2,
            },
            {
                'title': 'Game Developer',
                'category': 'gaming',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 800000,
                'description': 'Create games using C++ and Unity.',
                'requirements': 'C++ programming, game development basics.',
                'responsibilities': 'Develop game features, implement graphics.',
                'required_skills': ['C++', 'Unity', 'Graphics Programming', 'Game Physics'],
                'positions_available': 2,
            },
            
            # IoT
            {
                'title': 'IoT Engineer',
                'category': 'iot',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 450000,
                'salary_max': 800000,
                'description': 'Build Internet of Things solutions.',
                'requirements': 'Embedded systems, basic electronics.',
                'responsibilities': 'Develop IoT devices, implement connectivity.',
                'required_skills': ['C/C++', 'Python', 'MQTT', 'Raspberry Pi/Arduino'],
                'positions_available': 2,
            },
            
            # Design
            {
                'title': 'UI/UX Designer',
                'category': 'design',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 600000,
                'description': 'Create beautiful user interfaces and experiences.',
                'requirements': 'Design tools knowledge, basic UX principles.',
                'responsibilities': 'Design UI mockups, create prototypes, conduct user research.',
                'required_skills': ['Figma', 'Adobe XD', 'UI Design', 'UX Research'],
                'positions_available': 2,
                'is_featured': True,
            },
            {
                'title': 'Blender Artist',
                'category': 'design',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 600000,
                'description': 'Create 3D models and animations.',
                'requirements': 'Blender knowledge, basic 3D concepts.',
                'responsibilities': 'Create 3D models, animate characters, design environments.',
                'required_skills': ['Blender', '3D Modeling', 'Animation', 'Texturing'],
                'positions_available': 1,
            },
            {
                'title': 'Shopify Developer',
                'category': 'web',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 600000,
                'description': 'Build e-commerce stores on Shopify platform.',
                'requirements': 'Shopify knowledge, Liquid templating.',
                'responsibilities': 'Develop Shopify stores, customize themes, integrate apps.',
                'required_skills': ['Shopify', 'Liquid', 'HTML5', 'CSS3', 'JavaScript'],
                'positions_available': 2,
            },
            {
                'title': 'Photoshop Designer',
                'category': 'design',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 300000,
                'salary_max': 500000,
                'description': 'Create graphics and edit images.',
                'requirements': 'Photoshop knowledge, design principles.',
                'responsibilities': 'Create graphics, edit images, design layouts.',
                'required_skills': ['Photoshop', 'Illustrator', 'Design', 'Typography'],
                'positions_available': 2,
            },
            {
                'title': 'Figma Designer',
                'category': 'design',
                'employment_type': 'full_time',
                'experience_level': 'fresher',
                'salary_min': 350000,
                'salary_max': 600000,
                'description': 'Create UI/UX designs using Figma.',
                'requirements': 'Figma knowledge, UI/UX principles.',
                'responsibilities': 'Design UI mockups, create prototypes, collaborate with developers.',
                'required_skills': ['Figma', 'UI Design', 'Prototyping', 'Design Systems'],
                'positions_available': 2,
            },
        ]
        
        created_count = 0
        updated_count = 0
        
        for job_data in jobs_data:
            category = category_objs[job_data['category']]
            slug = slugify(job_data['title'])
            
            # Set deadline to 3 months from now
            deadline = date.today() + timedelta(days=90)
            
            job_defaults = {
                'category': category,
                'description': job_data['description'],
                'requirements': job_data['requirements'],
                'responsibilities': job_data['responsibilities'],
                'employment_type': job_data.get('employment_type', 'full_time'),
                'experience_level': job_data.get('experience_level', 'fresher'),
                'location': 'Remote (Work From Home)',
                'salary_min': job_data.get('salary_min'),
                'salary_max': job_data.get('salary_max'),
                'salary_currency': 'INR',
                'required_skills': job_data['required_skills'],
                'application_deadline': deadline,
                'positions_available': job_data.get('positions_available', 2),
                'is_active': True,
                'is_featured': job_data.get('is_featured', False),
                'is_remote': True,
            }
            
            job, created = Job.objects.update_or_create(
                slug=slug,
                defaults=job_defaults
            )
            
            if created:
                created_count += 1
                self.stdout.write(self.style.SUCCESS(f'Created: {job.title}'))
            else:
                updated_count += 1
                self.stdout.write(self.style.WARNING(f'Updated: {job.title}'))
        
        self.stdout.write(self.style.SUCCESS(
            f'\n✅ Import Complete!\n'
            f'   Created: {created_count} jobs\n'
            f'   Updated: {updated_count} jobs\n'
            f'   Total: {created_count + updated_count} jobs'
        ))