import json

technologies = []

# Add more categories and technologies
categories = {
    'Frontend': [
        ("React", "JavaScript Frameworks", "⚛️", 98, "A JavaScript library for building user interfaces"),
        ("Vue.js", "JavaScript Frameworks", "💚", 92, "Progressive JavaScript framework for building UIs"),
        ("Angular", "JavaScript Frameworks", "🅰️", 88, "Platform for building mobile and desktop web applications"),
        ("Next.js", "React Frameworks", "▲", 95, "React framework for production with SSR and SSG"),
        ("TypeScript", "Languages", "📘", 94, "Typed JavaScript at any scale"),
        ("Tailwind CSS", "CSS Frameworks", "🎨", 93, "Utility-first CSS framework for rapid UI development"),
        ("Svelte", "JavaScript Frameworks", "🟢", 87, "Cybernetically enhanced web apps"),
        ("Nuxt.js", "Vue Frameworks", "🟢", 86, "Intuitive Vue framework"),
        ("Gatsby", "React Frameworks", "🚀", 84, "Blazing fast static site generator"),
        ("Remix", "React Frameworks", "📦", 83, "Full stack web framework"),
        ("SolidJS", "JavaScript Frameworks", "⚡", 82, "Declarative JavaScript library"),
        ("Qwik", "JavaScript Frameworks", "⚡", 81, "Instant loading web apps"),
        ("Alpine.js", "JavaScript Frameworks", "🏔️", 79, "Lightweight JavaScript framework"),
        ("Preact", "JavaScript Frameworks", "⚛️", 78, "Fast 3kB React alternative"),
        ("Lit", "Web Components", "🔥", 77, "Simple library for building web components"),
        ("Stencil", "Web Components", "⚡", 76, "Web component compiler"),
        ("Bootstrap", "CSS Frameworks", "🎨", 90, "Popular CSS framework for responsive design"),
        ("Material UI", "Component Libraries", "🎨", 88, "React components for faster development"),
        ("Chakra UI", "Component Libraries", "🎨", 86, "Simple modular component library"),
        ("Ant Design", "Component Libraries", "🐜", 85, "Enterprise-class UI design language"),
        ("Shadcn/ui", "Component Libraries", "✨", 89, "Beautifully designed components"),
        ("Framer Motion", "Animation", "🎬", 85, "Production-ready animation library"),
        ("GSAP", "Animation", "🎬", 84, "Professional-grade animation"),
        ("Three.js", "3D Graphics", "🎮", 86, "JavaScript 3D library"),
        ("D3.js", "Data Visualization", "📊", 87, "Data-driven documents"),
        ("Chart.js", "Data Visualization", "📈", 85, "Simple charting library"),
        ("Recharts", "Data Visualization", "📊", 83, "Composable chart library"),
        ("Redux", "State Management", "🔄", 89, "Predictable state container"),
        ("Zustand", "State Management", "🐻", 88, "Small and fast state management"),
        ("Jotai", "State Management", "⚛️", 85, "Primitive and flexible state"),
        ("MobX", "State Management", "🔄", 84, "Simple scalable state management"),
        ("Recoil", "State Management", "⚛️", 82, "Experimental state management"),
        ("Webpack", "Build Tools", "📦", 90, "Module bundler"),
        ("Vite", "Build Tools", "⚡", 92, "Next generation frontend tooling"),
        ("Rollup", "Build Tools", "📦", 86, "Module bundler for JavaScript"),
        ("Parcel", "Build Tools", "📦", 84, "Blazing fast bundler"),
        ("ESLint", "Linting", "🔍", 88, "Pluggable JavaScript linter"),
        ("Prettier", "Formatting", "💅", 89, "Opinionated code formatter"),
        ("Jest", "Testing", "🃏", 90, "Delightful JavaScript testing"),
        ("Vitest", "Testing", "⚡", 87, "Blazing fast unit test framework"),
        ("Cypress", "Testing", "🌲", 88, "Fast testing framework"),
        ("Playwright", "Testing", "🎭", 89, "Reliable end-to-end testing"),
        ("React Testing Library", "Testing", "🧪", 87, "Simple testing utilities"),
        ("Storybook", "Documentation", "📚", 86, "UI component workshop"),
        ("Ember.js", "JavaScript Frameworks", "🔷", 78, "Framework for ambitious web developers"),
        ("Backbone.js", "JavaScript Frameworks", "🔶", 72, "Lightweight MVC framework"),
        ("Meteor.js", "JavaScript Frameworks", "☄️", 70, "Full-stack JavaScript platform"),
        ("Handlebars", "Templating", "📝", 75, "Minimal templating language"),
        ("Pug", "Templating", "🐶", 73, "High-performance template engine"),
    ],
    'Backend': [
        ("Python", "Languages", "🐍", 99, "Programming language that lets you work quickly"),
        ("Node.js", "Runtime", "🚀", 96, "JavaScript runtime built on Chrome's V8"),
        ("Django", "Web Frameworks", "🎯", 91, "High-level Python web framework"),
        ("Flask", "Web Frameworks", "🌶️", 88, "Lightweight Python web framework"),
        ("FastAPI", "Web Frameworks", "⚡", 89, "Modern Python web framework"),
        ("Express.js", "Web Frameworks", "🚂", 94, "Fast web framework for Node.js"),
        ("NestJS", "Web Frameworks", "🦁", 87, "Progressive Node.js framework"),
        ("Spring Boot", "Web Frameworks", "🌱", 90, "Java framework for microservices"),
        ("Laravel", "Web Frameworks", "⚙️", 89, "PHP web framework"),
        ("Ruby on Rails", "Web Frameworks", "💎", 86, "Web application framework"),
        ("Go", "Languages", "🔵", 92, "Statically typed compiled language"),
        ("Rust", "Languages", "🦀", 90, "Performance-focused language"),
        ("Java", "Languages", "☕", 94, "Object-oriented programming language"),
        ("C#", "Languages", "🔷", 91, "Modern object-oriented language"),
        ("PHP", "Languages", "🐘", 87, "Server-side scripting language"),
        ("Kotlin", "Languages", "🎯", 85, "Modern JVM language"),
        ("Swift", "Languages", "🦅", 86, "iOS development language"),
        ("GraphQL", "API", "📊", 91, "Query language for APIs"),
        ("REST API", "API", "🔌", 96, "Architectural style for APIs"),
        ("gRPC", "API", "🔌", 85, "High-performance RPC framework"),
        ("WebSocket", "API", "🔄", 88, "Real-time communication protocol"),
        ("JWT", "Authentication", "🔐", 89, "JSON Web Tokens"),
        ("OAuth", "Authentication", "🔑", 90, "Open authorization protocol"),
        ("ASP.NET Core", "Web Frameworks", "🔷", 86, "Cross-platform framework"),
        ("Fiber", "Web Frameworks", "⚡", 80, "Express-inspired framework for Go"),
        ("Actix Web", "Web Frameworks", "🦀", 82, "Powerful Rust framework"),
        ("Scala", "Languages", "🔴", 78, "Scalable language"),
        ("Elixir", "Languages", "💧", 79, "Dynamic functional language"),
        ("Phoenix", "Web Frameworks", "🔥", 81, "Productive web framework"),
        ("Haskell", "Languages", "📚", 72, "Purely functional language"),
    ],
    'Database': [
        ("PostgreSQL", "Relational", "🐘", 94, "Advanced open-source relational database"),
        ("MySQL", "Relational", "🐬", 92, "Popular open-source relational database"),
        ("MongoDB", "NoSQL", "🍃", 91, "Document database"),
        ("Redis", "In-Memory", "📀", 93, "In-memory data structure store"),
        ("Cassandra", "NoSQL", "🔮", 84, "Distributed NoSQL database"),
        ("Elasticsearch", "Search", "🔍", 88, "Distributed search engine"),
        ("DynamoDB", "NoSQL", "📊", 87, "AWS NoSQL database"),
        ("Firebase", "Real-time", "🔥", 89, "Real-time NoSQL database"),
        ("Supabase", "Relational", "📦", 86, "Open-source Firebase alternative"),
        ("SQLite", "Embedded", "📁", 85, "Embedded SQL database"),
        ("Oracle", "Relational", "🔶", 84, "Enterprise relational database"),
        ("SQL Server", "Relational", "🪟", 86, "Microsoft relational database"),
        ("MariaDB", "Relational", "🐬", 85, "MySQL fork"),
        ("CouchDB", "NoSQL", "🛋️", 80, "JSON-based document database"),
        ("Neo4j", "Graph", "🔗", 83, "Graph database"),
        ("ArangoDB", "Multi-model", "🔷", 82, "Multi-model database"),
        ("InfluxDB", "Time-series", "📈", 82, "Time-series database"),
        ("TimescaleDB", "Time-series", "⏱️", 81, "Time-series PostgreSQL"),
        ("ClickHouse", "Analytics", "📊", 84, "Column-oriented database"),
        ("Snowflake", "Cloud", "❄️", 87, "Cloud data platform"),
        ("BigQuery", "Cloud", "🔍", 88, "Google cloud data warehouse"),
        ("Redshift", "Cloud", "🔴", 86, "AWS cloud data warehouse"),
        ("CockroachDB", "Distributed", "🐞", 83, "Cloud-native distributed SQL"),
        ("TiDB", "NewSQL", "🔷", 82, "Distributed NewSQL database"),
    ],
    'DevOps': [
        ("Docker", "Containerization", "🐳", 97, "Platform for developing and shipping applications"),
        ("Kubernetes", "Orchestration", "⚙️", 95, "Container orchestration system"),
        ("AWS", "Cloud Providers", "☁️", 98, "Amazon Web Services"),
        ("Azure", "Cloud Providers", "☁️", 94, "Microsoft Azure cloud"),
        ("GCP", "Cloud Providers", "☁️", 93, "Google Cloud Platform"),
        ("Terraform", "Infrastructure", "🏗️", 92, "Infrastructure as Code"),
        ("Ansible", "Automation", "📦", 88, "Automation platform"),
        ("Jenkins", "CI/CD", "🔧", 90, "Automation server"),
        ("GitHub Actions", "CI/CD", "⚡", 94, "CI/CD automation"),
        ("GitLab CI", "CI/CD", "🦊", 91, "GitLab continuous integration"),
        ("CircleCI", "CI/CD", "🔵", 88, "Continuous integration platform"),
        ("ArgoCD", "CD", "🔵", 89, "Declarative GitOps CD"),
        ("Helm", "Package Manager", "🎩", 88, "Kubernetes package manager"),
        ("Istio", "Service Mesh", "🔗", 86, "Service mesh platform"),
        ("Prometheus", "Monitoring", "📊", 90, "Monitoring system"),
        ("Grafana", "Monitoring", "📈", 91, "Observability platform"),
        ("Datadog", "Monitoring", "🐕", 89, "Cloud monitoring platform"),
        ("New Relic", "Monitoring", "🔵", 87, "Observability platform"),
        ("ELK Stack", "Logging", "📊", 88, "Elasticsearch, Logstash, Kibana"),
        ("Splunk", "Logging", "🔍", 86, "Data platform for observability"),
        ("Pulumi", "Infrastructure", "🔷", 85, "Modern Infrastructure as Code"),
        ("Vagrant", "Virtualization", "📦", 80, "Development environment manager"),
        ("Chef", "Configuration", "🍳", 78, "Infrastructure automation"),
        ("Puppet", "Configuration", "🎭", 77, "Configuration management"),
    ],
    'AI/ML': [
        ("TensorFlow", "Frameworks", "🧠", 94, "Open-source ML platform"),
        ("PyTorch", "Frameworks", "🔥", 95, "Deep learning framework"),
        ("Keras", "Frameworks", "🧠", 90, "Deep learning API"),
        ("Scikit-learn", "Libraries", "📊", 92, "Machine learning library"),
        ("OpenCV", "Computer Vision", "👁️", 89, "Computer vision library"),
        ("Pandas", "Data Analysis", "🐼", 93, "Data manipulation library"),
        ("NumPy", "Scientific Computing", "🔢", 94, "Scientific computing library"),
        ("LangChain", "LLM", "🔗", 91, "Language model framework"),
        ("OpenAI", "LLM", "🤖", 96, "AI research and deployment"),
        ("Hugging Face", "LLM", "🤗", 93, "AI model hub"),
        ("LlamaIndex", "LLM", "🦙", 87, "Data framework for LLMs"),
        ("Transformers", "LLM", "🔄", 90, "Pre-trained models library"),
        ("JAX", "Frameworks", "⚡", 85, "Numerical computing library"),
        ("MXNet", "Frameworks", "🔷", 78, "Deep learning framework"),
        ("Caffe", "Frameworks", "☕", 72, "Deep learning framework"),
        ("Theano", "Frameworks", "🔢", 68, "Numerical computation library"),
    ],
}

# Build the technologies list
for category, techs in categories.items():
    for tech in techs:
        technologies.append({
            "name": tech[0],
            "category": category,
            "subcategory": tech[1],
            "icon": tech[2],
            "popularity": tech[3],
            "description": tech[4],
            "long_description": f"{tech[0]} is a leading {category.lower()} technology in the {tech[1]} space. It is widely used by developers worldwide for building modern, scalable applications.",
        })

# Save to JSON file
with open('technologies_data_full.json', 'w', encoding='utf-8') as f:
    json.dump(technologies, f, indent=2, ensure_ascii=False)

print(f"Generated {len(technologies)} technologies")